composer.json
index.php
src/Cms/Auth/LoginService.php
src/Cms/MiniRouter.php

전부 정리하지는 못했고, 아래 Config 에서 사용되는 변수는 외부에서 선언해 주어야 합니다.
```php
class Config
{
public static $DB_PARAMS = [];
public static $DOMAIN;
public static $MISC_URL;
public static $ACTIVE_URL;
public static $HTTP_HOST_LINK;
public static $SSL_HOST_LINK;
public static $UNDER_DEV = true;
public static function getConnectionParams($name)
{
if (isset(static::$DB_PARAMS[$name])) {
return static::$DB_PARAMS[$name];
}
if (!isset(static::$DB_PARAMS['default'])) {
throw new \Exception("Default DB connection parameters are missing.");
}
return static::$DB_PARAMS['default'];
}
}
```
업그레이드시 하위호환 이슈가 발생하며, 아래와 같이 수정이 필요합니다.
1.
LoginService::startSession()
=> LoginService::startCouchbaseSession(\Config::$COUCHBASE_SERVER_HOSTS)
2.
$app['debug'] = \Config::$UNDER_DEV;
3. …

Config 전역변수 정리 #1

---

.gitignore

Fixes the following PhpStorm warning:
> Ignored files found that are tracked: .ignore plugin found some files that are tracked with Git which are also listed in .gitignore file.

Unignore sample deploy target specification

---

src/Model/AdminMenu.php
src/Service/AdminMenuService.php

https://app.asana.com/0/235684600038401/381445095289849/f
태그로 권한이 관리되면서, 계정에 메뉴 권한이 직접적으로 할당되진 않았지만 해당 메뉴가 포함된 태그가 등록되면서 간접적으로 권한이 부여되는 경우가 있습니다.
이런 경우를 고려해서 전체 유저를 검색하는 기능이 없었기 때문에 이번에 추가했습니다.

Add AdminMenuService::getAllUserIds.

---

src/CmsServerApplication.php

Removed configurations in bootstrap that are no longer required since cms-server is separated.

Remove extraneous config

---

src/Service/AdminMenuService.php

**Issue**:
https://app.asana.com/0/235684600038401/381445095289849/f
**Changed**:
I added a condition checking is_use=1 at the function.
**How to test**:
- Run`curl -d '[1,"AdminMenu:getAllUserIds",1,0,{"1":{"i32":[TAG ID]}}]' -H "Accept: application/x-thrift" -X POST [CMS TEST HOST]`. (Replace [TAG ID] and [CMS TEST HOST] to test value)
- Check the result whether it contains only ids which is_use=1.

Fix AdminMenuService::getAllUserIds not to return unused ids

---

Dockerfile
Makefile
health.php
src/Service/AdminMenuService.php

Fix getAllUserIds not to return unused ids.
Add a health check page and Dockerfile.
Add Dockerfile. (#21) |  ec7b31378c76f373233255692cc6429a54add39b
Add health.php (#24) | 13238fdbe24aaa1949a5a386b30eb4a337b4ad8c
Fix AdminMenuService::getAllUserIds to return ids in used. (#23) | 285143d6d3b2982c52714c59e513e3c3fe41e731

Release v1.1.1

---

src/MiniRouter.php
src/Service/AdminAuthService.php

현재 authorize함수가 cms와 cms-sdk에 각각 구현되어 있는데 cms도 cms-sdk버전을 써버리면 어떨까 싶어서 수정해봤습니다. RPC호출이 있겠지만 localhost에서 처리하게하면 문제는 없을거 같아서요.

Replace authorize() using cms-sdk

---

composer.json
composer.lock
src/CmsServerApplication.php
src/Lib/AzureOAuth2Service.php
src/LoginController.php
src/Service/AdminAuthService.php
src/Service/AdminUserService.php
src/Service/LoginService.php
views/welcome.twig

cms-sdk 1.x와 2.x를 혼용하여 운영하기 위해 현재 운영중인 cms에 cms 2.x에 적용된 토큰기반 로그인 로직을 반영해야 합니다. 
수정 내용은 이전에 2.x 브랜치에 리뷰받은 내용과 거의 동일하며 추가로 cms-sdk 2.x를 사용하고 있었는데 1.x를 사용하게 되돌렸습니다.
배포 계획은 아래 정리해두었습니다.
https://app.asana.com/0/235684600038401/509512231774235

Use cms-sdk 1.x & add token based login

---

src/Service/AdminUserService.php

하나의 메뉴가 직접추가되었거나, 태그를 통해 간접적으로 유저에게 부여되서 메뉴가 중복으로 나타나는 버그가 있습니다.
기존 1.x에는 db에서 menu id의 리스트만 가져와서 array_unique로 간단히 처리하지만 지금은 array의 array구조라서 다소 복잡하게 처리되었습니다. 좀 더 간단한 방법을 제안해주셔도 좋을것 같습니다.

Fix menu duplication

---

src/Service/AdminAuthService.php

getHashesFromMenus에서 null이 포함될 수 있는데 (menu는 있으나 hash가 없는 경우 array_map결과로 null이 추출되어 들어감) 그런 경우 getHashesFromMenus결과를 Thrift로 내보내면서 예외가 발생합니다.  
array_filter를 적용해서 문제를 수정했습니다.

Remove null hashes from getHashesFromMenus

---

src/Controller/LoginController.php

/login페이지에 `redirect` 파라메터를 받으면 페이지를 보여주지 않고 바로 azure authorize 엔드포인트를 호출하도록 기능을 추가하였습니다.
이는 추후 리뷰할 cms-sdk PR에서 만료된 로그인 토큰의 자동 갱신을 위해 cms의 /login 엔드포인트를 사용하기 위함입니다.
https://app.asana.com/0/235684600038401/596133256149552

Add `redirect` parameter at /login

---

src/Lib/AzureOAuth2Service.php
src/LoginController.php

2.x에서 refresh token을 활용할수 있게하기위해 기존 1.x에서 refresh token을 쿠키에 저장하게 수정했습니다.

[1.x] Save refresh token in cookies (2.x compatibility)

---

composer.json
composer.lock
src/Controller/LoginController.php
src/Lib/AzureOAuth2Service.php
src/Service/LoginService.php
tests/AzureOAuth2ServiceTest.php

토큰 만료시 /token-refresh 에서 연장하도록 수정하였습니다.
https://app.asana.com/0/235684600038401/600156742639752
* /token-refresh 추가
* /login-authorize 제거
* 로그인시 Refresh 토큰 저장
* curl 사용로직 GuzzleHttp로 리펙터링
`/token-refresh`가 쿠키의 토큰 값들을 변경해야함에도 GET으로 구현해야 했습니다. 
이유는 `/token-refresh`가  User Agent의 redirect를 통해 접근되고 있기 때문입니다. (Refresh 토큰 쿠키가 `/token-refresh`에서만 접근가능하기 때문에 Server Side에서 호출이 불가능합니다.)
이는 `/token-introspect`가 Server Side에서 POST로 호출되는것과 차이가 있습니다.

Add /token-refresh endpoint 

---

src/Controller/LoginController.php
src/Lib/AzureOAuth2Service.php
src/Service/LoginService.php

환경변수 `TEST_ID` 가 설정되어 Azure로그인을 생략하도록 하면 제대로 로그인되지 않던 문제를 수정했습니다.
```php
// 문제가 된 부분 (기존 소스 L38)
// time() + 60 * 60 * 24 * 30 가 되어야 함
'expires_on' => 60 * 60 * 24 * 30
```
- test인 경우는 로그아웃 시 Azure 로그아웃을 생략하도록 수정
- LoginService::login -> LoginService::addUserIfNotExists 이름 변경
> 정확히 어떤 동작을 하는지, 의도를 가진 함수인지 애매해서
- LoginService::createLoginResponse와 Login::createLoginCookies 통합
> array_filter와 루프를 제거하고, 명시적으로 setCookie를 반복 호출하는게 한 눈에 파악하기 좋다고 생각해서 (기존 소스 L64, L87)
- php-cs-fixer 적용

Fix the broken test mode (wrong expired time)

---

src/Service/LoginService.php

Access Token 쿠키의 유효기간이 token자체의 유효기간과 같아서 유효기간 만료체크가되지 않고 바로 로그인으로 이동되고 있는 문제를 수정했습니다.
동시에 기존에는 개별쿠키에 유효기간을 세팅하던 것에서, 로그인에 대한 유효기간에 맞추어 모두 동일하게 변경했습니다. (`$login_expires_on`) 그리고 이 로그인의 유효기간은 refresh token의 유효기간과 동일하게 볼수 있으므로 refresh token의 유효기간에서 가져옵니다.

Fix token refresh failure due to cookie expiration

---

bin/setup.sh
phinx/seeds/Tag.php
src/Service/AdminTagService.php
tests/AdminTagServiceTest.php

https://github.com/ridi/cms-sdk/pull/44 를 CMS에 적용한 내용입니다.
CMS-SDK가 머지되면 composer.lock 업데이트후 이것도 merge할 생각입니다.

Add `getAdminTag` api

---

src/Service/AdminAuthService.php
tests/AdminAuthServiceTest.php

This fixes 500 error during `/authorize` call when `TEST_ID` is set in ENV.

Fix authorize error when TEST_ID set

---

CHANGELOG.md
src/Service/AdminAuthService.php
src/Service/LoginService.php
web/index.php

기존 개발환경에서 인증과정을 생략하기 위해 `TEST_ID` 환경 변수를 사용했습니다.
각자 서버를 설정했기 때문에 `TEST_ID`를 개인별로 설정이 가능했지만, 이번에 공용 CMS 서버를 사용하면서 개별 설정이 불가능해졌습니다.
`TEST_AUTH_DISABLE`가 켜진 경우, 요청 도메인을 참조해서 로그인 시킬 유저 아이디를 결정하도록 수정했습니다.
`TEST_AUTH_DISABLE`가 켜진 경우, request의 host에 따라 환경변수 `TEST_ID`를 설정합니다.  
host가 admin.{id}.dev.ridi.io 형태인 경우에만 `{id}`에 해당하는 값으로 설정합니다.  
Thrift요청을 받을 땐 도메인에 유저 정보가 담겨있지 않아 처리가 어렵습니다.  
`TEST_AUTH_DISABLE`가 켜진 경우 인증, 인가 전부 생략하도록 수정했습니다.   
다만 단순히 전부 무시하면 #51 의 문제가 재발하게 되는데,  token의 유무는 체크하여 버그가 재발하는 것을 방지했습니다

If set env TEST_AUTH_DISABLE, set TEST_ID also

---

src/Service/AdminAuthService.php
tests/AdminAuthServiceTest.php

This PR is a suggestion of how to implement tests in our codebase.
It just extends [`Pimple/container`](https://github.com/silexphp/Pimple) for dependency injection. 
If this approach is acceptable, then I will apply this to entire `AdminAuthService` class.
I think this is a bit simpler than introducing ServiceProvider concept to the whole codebase.
Just take a look and share your ideas.

Suggestion for testing with DI

---

CHANGELOG.md

This release is for `authorizeByTag` API.
https://app.asana.com/0/314089093619591/615078255787233
Fix authorize error when TEST_ID set (#53)
Support login with test domain when TEST_AUTH_DISABLE is set (#55)
Add `authorizeByTag` API support with the update of cms-sdk v2.3.1-rc.1

Release v2.1.8

---

views/base.twig
views/me.twig
views/welcome.twig

https://app.asana.com/0/0/658456569210247/f
Applied newly implemented menu component of [*cms-ui*](https://github.com/ridi/cms-ui). `index_new.twig` need to be copied from *cms-sdk* because it was not possible to extend menu part only without rewriting code.

Apply CMS-UI

---

config/config.php
src/Controller/AuthController.php
src/Lib/AzureOAuth2Service.php
src/Service/LoginService.php

https://app.asana.com/0/235684600038401/672522917102718/f
1. Set the upper domain for the token cookies.
This is backward compatible since it applies only when the request domain starts with `auth.`
2. Added a new `AZURE_REDIRECT_PATH` ENV value to be able to build Azure redirect URL according to the site domain.

Use auth subdomain

---

CHANGELOG.md

This release is mainly for Shop Admin migration.
- Add a new API `introspectToken` (#64)
- Use auth subdomain (#62)

Release v2.1.13

---

views/base.twig

이슈: https://app.asana.com/0/0/688275289313548/f
Firefox 브라우저에서 CMS UI의 메뉴가 스크롤되지 않는 버그가 있었습니다. [Firefox의 flexbox에 관련된 문제](https://stackoverflow.com/questions/44948158/flexbox-overflow-issue-in-firefox)로 해당 버그는 [CMS UI에서 수정](https://github.com/ridi/cms-ui/commit/0fd4c60fde9d4d2ab37e84d756a7ad6ee3fcd812)되었고, 향후 버그수정의 빠른 적용을 위해 CMS UI의 참조 버전을 특정 버전(0.3.1)에서 0.3.x로 변경했습니다.
감사합니다.

Fix CMS UI menu scrolling bug

---

.gitignore
bin/setup.sh
phinx/migrations/20170810100141_init_cms.php
phinx/migrations/20180502030243_add_tag_display_name_column.php
phinx/migrations/20180523061119_add_group.php
phinx/migrations/20180524084101_add_group_view.php
phinx/seeds/Group.php
phinx/seeds/GroupTag.php
phinx/seeds/GroupUser.php
phinx/seeds/Tag.php
src/Model/AdminGroup.php
src/Model/AdminTag.php
src/Model/AdminUser.php
src/Service/AdminAuthService.php
src/Service/AdminUserService.php
tests/AdminAuthServiceTest.php
tests/AdminGroupModelTest.php
tests/AdminUserServiceTest.php

This PR introduces user group.
https://app.asana.com/0/314089093619591/665707044394720
- Added new `tb_admin2_group` table. (and many to many relationship tables)
- Added a view `vw_admin2_user_tag_group_joined` which is a union view of `tb_admin2_user_tag` and `tb_admin2_group_tag`.
- This is for a better readability and simplicity of the codebase.
- Any other name suggestion is welcome :)
- `authorizeByTag` API now searches `vw_admin2_user_tag_group_joined` view to include tags in groups.
CMS-Admin as well will add the user group feature for CRUD operations.

Add user group for tags

---

phinx/seeds/Menu.php
phinx/seeds/TagMenu.php
src/Service/AdminUserService.php
tests/AdminUserServiceTest.php

This is a follow-up PR of #68.
Fix the left menu list to include menus over groups.

User menus includes tags over groups

---

src/Service/AdminAuthService.php
src/Service/AdminMenuService.php
src/Service/AdminMenuTree.php
src/Service/AdminUserService.php
tests/AdminAuthServiceTest.php
tests/AdminMenuTreeTest.php

https://app.asana.com/0/235684600038401/678316075713797/f
When requesting menus for the menu UI, the result has contained only exact menus that are permitted to the current user without associated parent menus. As a result, **menus are positioned to unexpected parents' children**.
This PR will fix the problem by **exposing associated parent menus without the permission**.
- The menus have url of `#` will be regarded as potential parent menus.

Fix unexpected menu positioning

---

src/Controller/AuthController.php
src/Service/Auth/AuthenticationServiceProvider.php
src/Service/Auth/Authenticator/OAuth2Authenticator.php
src/Service/Auth/OAuth2/Client/AzureClient.php
src/controllers.php
tests/unit/Controller/AuthControllerTest.php
tests/unit/Mock/MockOAuth2Client.php
tests/unit/Service/Auth/Authenticator/OAuth2AuthenticatorTest.php

https://app.asana.com/0/235684600038401/729310572333829/f
- 기존:  
/auth/oauth2/azure/authorize 에서 code grant, refresh grant 방식의 인증 둘 다 수행
- 변경:  
code grant는 새로 /auth/oauth2/azure/code 에서, refresh grant는 그대로 기존 /auth/oauth2/auzre/authorize 에서 수행하도록 변경  
로그인 검증이나 refresh 토큰 갱신은 기존처럼 ~/azure/authorize에서 처리되는데, 이제 인증에 실패하면 Azure 인증으로 이동시키지 않고 CMS 로그인 페이지로 이동시킵니다.  
Azure 인증으로 이동하는 부분은 ~/azure/code로 옮겨졌습니다. 이제 로그인 페이지에서 로그인 버튼을 누를 때는 ~/azure/authorize 대신 ~/azure/code로 이동됩니다.

WIP: Fix wrong OAuth2 authorize

---

CHANGELOG.md
src/Service/Auth/OAuth2/Client/AzureClient.php

- Fix to refresh token at `/auth/oauth2/authorize` (#78)
- Fix test server login id error 780dff2
- Configure viewport for mobile UI (#77)
- Make test id available in `introspectToken` a65b36a4035213820786ce4eafc797d4f7dbaed8
- Log details on azure api fail

Release v2.1.19

---

src/Controller/AuthController.php
src/Service/Auth/AuthMiddleware.php
src/Service/Auth/AuthenticationServiceProvider.php
src/Service/Auth/Authenticator/OAuth2Authenticator.php
src/Service/Auth/OAuth2/Client/AzureClient.php
src/Service/Auth/Session/CookieSessionStorage.php
src/Service/ThriftServiceProvider.php
tests/unit/Controller/AuthControllerTest.php

Fixed `Expired token` exception during `/authorize` call. 
It happens when token cookie exists but has expired.
- `createCredential` now refreshes tokens instead of just returning access token.
- Added missing exception handlings.

Fix access token expired exception

---

bin/deploy.sh

https://travis-ci.org/ridi/cms/builds/496853164
deploy 시 기존에 CI 트리거 url이 gitlab.ridi.io에서 gitlab.com 마이그레이션 진행 후 변경되어 URL이 유효하지 않습니다
gitlab ci 트리거 url 을 변경하였습니다.
기존: gitlab.ridi.io
변경: gitlab.com

Updated a legacy; gitlab.ridi.io -> gitlab.com

---

src/Service/AdminAuthService.php

테스트환경에서 `Signed in with Test`로 인증받았어도 authorizeByTag가 Azure인증을 체크해서 Malformed Token 예외를 발생시키는 버그가 있었습니다.
authorizeByTag가 테스트 인증인지 먼저 체크해서 introspectToken을 건너뛰어야 하는데, 체크를 introspectToken 호출 후 수행하도록 되어있었습니다.
여태까지 발견안된 것이 신기한 버그입니다(...)

Fix the bug that prevents authorizing-by-tag on dev environment

---

.env.docker
composer.json
src/Controller/AuthController.php
src/controllers.php
tests/unit/Controller/AuthControllerTest.php

리디셀렉트 어드민 프론트엔드를 분리하고 있는데, 백엔드를 거치지 않고 직접 CMS와 통신해서 인증처리를 하려고 합니다. 토큰을 갱신해야 할 경우에 사용할 API가 없어서 추가했습니다.
기존에 비슷한 역할로는 `/auth/oauth2/authorize`가 있습니다. 하지만 이건 cms-sdk에서 인증 실패 판별 후 유저로 하려금 인증을 받아오라고 보내는 리다이렉션 전용 url 입니다.  지금 필요한 기능은 1) 토큰을 갱신하고, 2) 갱신이 불가능한 경우 (로그인 페이지 302 응답을 보내는 것이 아니라) 401 응답을 내어주는 토큰 갱신 전용 API입니다.

Add token API

---

Dockerfile
config/apache2/security.conf
src/Controller/AuthController.php
tests/unit/Controller/AuthControllerTest.php
views/login.twig
web/static/css/admin/login.css

https://app.asana.com/0/939760765810445/1127194147283316/f
-  login/logout 페이지 내 return_url 파라미터에서 발생하는 reflected xss 가 발생하지 않도록 필터링함수를 추가하였습니다. (getFilteredReturnUrl) 
- 추가로 발생할 수 있는 open redirect 취약점을 예방하기 위해, `.ridibooks.com`에서만 redirect할 수 있도록 수정하였습니다.

open redirect 과 reflected xss 취약점 수정

---

src/app.php
src/controllers.php

https://app.asana.com/0/939760765810445/1127194147283316/f
- 해당 제보(open redirect, reflected xss) 의 장기적 대응 PR입니다. 
- 단기적 대응은 #94 에서 진행 중입니다. 
cms after 미들웨어가 추가되었습니다.
- response 헤더에 다음과 같은 내용이 모든 response header 에 추가됩니다. 
> X-Frame-Options: DENY
> X-Content-Type-Options: nosniff
> X-XSS-Protection: 1; mode=block
> Content-Security-Policy-Report-Only: default-src 'self'; report-uri https://gyx3tts4g8.execute-api.ap-northeast-2.amazonaws.com/default/perf-csp-reports-lambda;
- csp reporting을 위해 다음과 같은 uri가 추가되었습니다.  
- `https://gyx3tts4g8.execute-api.ap-northeast-2.amazonaws.com/default/perf-csp-reports-lambda`
- 해당 url은 퍼포먼스팀 개발환경에서 동작하는 lamba function 이며, api gateway로 endpoint를 생성하였습니다.
- [api gateway aws 프리티어 사용량](https://aws.amazon.com/ko/api-gateway/pricing/)을 초과하지 않을것으로 예상됩니다. …

Apply a security header with CMS Middleware

---

src/Controller/AuthController.php

https://app.asana.com/0/1127742852096038/1130217216318990/f
return_url에서 backslash 필터링이 되지 않아 open redirect 취약점 발생합니다.
`\` 를 escape 하도록  필터링을 추가하였습니다. 
`&`를 escape하지 않도록 예외를 추가하였습니다.

getFilteredReturnUrl  내 backslash 필터링 추가 

---

.travis.yml
Dockerfile
src/app.php

https://app.asana.com/0/1163015767457465/1163249052485321/f
- sentry csp report 삭제
- deprecated된 sudo 태그를 삭제하였습니다.
- 오타 수정 | after_scrpt -> after_script 
- npm 설치 시, --unsafe-perm=true 파라미터 추가 
- 패키지 설치 시, uid, gid 를 전환하지 않습니다. 
-  https://docs.npmjs.com/misc/config#unsafe-perm
-  https://geedew.com/What-does-unsafe-perm-in-npm-actually-do/

csp 리포트 제거 및 ci  설정 업데이트
