.htaccess, server/CmsServerApplication.php
기존에 잘못된 정적 파일 요청시 url라우팅을 시도하면서 예외가 발생하던 상황을 수정
=> Prevent routing when requested static files.

src/LoginController.php, src/Service/AdminUserService.php, src/Service/LoginService.php, views/login.twig, views/me.twig, views/welcome.twig
이전 로그인 방식을 제거했습니다.
- 변경 안내 문구, ID & PW 입력 UI 삭제
- azure로그인은 성공했지만 cms db상에 유저가 없는 경우 새로 추가
=> Remove the old logins.

composer.json, composer.lock, index.php, src/CmsServerApplication.php
Issue: https://github.com/ridibooks/cms/issues/18
This uses `jguyomard/silex-capsule-eloquent` package, a service provider capsulizing database.
=> Use a capsule service provider.

Dockerfile, Makefile
Updated simple Dockerfile using [ridibooks/performance-apache-base](https://hub.docker.com/r/ridibooks/performance-apache-base/) image.
=> Add Dockerfile.

health.php
Added `health.php` to be checked by HAProxy as we are planing to extract CMS server from the rest of other services.
=> Add health.php

composer.json, composer.lock, index.php, src/CmsServerApplication.php, src/LoginController.php, src/Service/AdminAuthService.php, src/Service/AdminUserService.php, src/Service/LoginService.php, views/welcome.twig
**변경사항:**
- `cms-sdk` 버전을 업데이트 (네임스페이스 변경)
- MD 요청사항 반영
=> cms-sdk 2.0 적용

composer.json, composer.lock, config/config.php, src/app.php, web/index.php
CMS-SDK 2.2 적용했습니다.
주요 변경사항은 https://github.com/ridi/cms-sdk/pull/34 에 따른 CmsApplication에 config주입 로직 변경입니다.
=> Make cms-sdk 2.2 compatible

src/Controller/LoginController.php, src/Service/LoginService.php
테스트를 위해 `DEBUG` env 값이 1이면 cookie에 secure옵션을 사용하지 않도록 변경했습니다.
=> In dev env, remove secure option from cookie

src/Controller/LoginController.php, src/Lib/AzureOAuth2Service.php, src/Service/LoginService.php
CMS로그아웃시 Azure에서로 로그아웃되도록 수정했습니다. 기존에 logout을 시켜도 id/passwd 재입력없이 다시 로그인 가능한 문제를 수정합니다.
=> Azure logout

src/LoginController.php, src/MiniRouter.php, src/Service/AdminAuthService.php
2.x처럼`TEST_AUTH_DISABLE` 환경 변수를 추가했습니다.
그리고 토큰 쿠키 추가, 삭제 시 문제가 되는 2.x에 있던 버그를 수정했습니다.
=> Add test env, and fix the wrong cookie set and clear

CHANGELOG.md
Add `CHANGELOG.md` for making easier to see precisely what changes between each changes.
=> Release v2.1.7

composer.json, composer.lock, src/Service/AdminAuthService.php, src/Service/AdminTagService.php, src/Thrift/AdminAuthThrift.php, tests/AdminAuthServiceTest.php
This implements `authorizeByTag`, which is added at https://github.com/ridi/cms-sdk/pull/48.
=> Add authorizeByTag

src/app.php
Not sure if this is the best place to put this code, but I think Sentry should be initialized as early as possible.
=> Fix sentry not working

CHANGELOG.md
- Update test server URL for platform team | f7658f4
- Replace menu component with CMS UI (#61)
- Fix invalid test assert | 39c62eb
- Fix sentry not working (#60)
=> Release v2.1.12

.php_cs, CHANGELOG.md, composer.json, composer.lock, src/Controller/AuthController.php, src/Controller/CommonController.php, src/Lib/AzureOAuth2Service.php, src/Model/AdminMenu.php, src/Model/AdminMenuAjax.php, src/Model/AdminTag.php, src/Model/AdminUser.php, src/Service/AdminAuthService.php, src/Service/AdminMenuService.php, src/Service/AdminTagService.php, src/Service/AdminUserService.php, src/Service/LoginService.php, src/Service/ThriftServiceWrapper.php, src/Thrift/AdminAuthThrift.php, src/Thrift/AdminMenuThrift.php, src/Thrift/AdminTagThrift.php, src/Thrift/AdminUserThrift.php, tests/AdminAuthServiceTest.php
Implemented new API `introspectToken` in response to https://github.com/ridi/cms-sdk/pull/51
=> Add token introspect

config/config.php, web/index.php
https://app.asana.com/0/235684600038401/724407230130406/f
=> Set domain "admin.*.test.ridi.io" enable test

CHANGELOG.md
- Set domain "admin.*.test.ridi.io" enable test #72 
- Refactor LoginService to multiple Authenticators #58
=> Release v2.1.16

src/LoginController.php
Note that this PR merges into 1.x branch.
- Change cookie domain to be compatible with 2.x
- Clear old cookies
- Shorten the cookie duration.
=> Change cookie domain to be compatible with 2.x

CHANGELOG.md
https://app.asana.com/0/235684600038401/726274713560091/f
- Use 'mailNickName' for azure id instead of 'unique_name' 94ec73a
=> Release v2.1.18

views/base.twig
Added viewport meta tag to use appropriate size & scale for rendering in mobile screen.
=> Configure viewport for mobile UI

CHANGELOG.md
- Fix access token expired exception (#80)
=> Release v2.1.20

CHANGELOG.md
- Fix token expired exception on authorize call over thrift  9d48998
=> Release v2.1.21

composer.json, composer.lock, phinx/migrations/20170810100141_init_cms.php, phinx/migrations/20180717033024_add_email_column.php, phinx/seeds/User.php, src/Controller/AuthController.php, src/Controller/CommonController.php, src/Model/AdminUser.php, src/Service/AdminAuthService.php, src/Service/AdminUserService.php, src/Service/Auth/Authenticator/BaseAuthenticator.php, src/Service/Auth/Authenticator/OAuth2Authenticator.php, src/Service/Auth/Authenticator/PasswordAuthenticator.php, src/Service/Auth/Authenticator/TestAuthenticator.php, src/Service/Auth/OAuth2/Client/AzureClient.php, src/Service/Auth/OAuth2/Client/OAuth2ClientInterface.php, tests/AdminUserServiceTest.php, tests/unit/Mock/MockAuthenticator.php, tests/unit/Mock/MockOAuth2Client.php, tests/unit/Service/Auth/Authenticator/OAuth2AuthenticatorTest.php
https://app.asana.com/0/314089093619591/745947642334722
- Add `email` column in user DB.
- The return of `getUser` API includes user email.
- Update username and email with the information retrieved from Azure after login.
=> Add email in user DB and update user info on login

CHANGELOG.md, src/Service/ThriftServiceProvider.php
- Add /v2 endpoint for thrift e4ca589bda1c934a7a2f9fa9399e0e004b5ae8e0
=> Release v2.1.24

web/robots.txt
Added `robots.txt` to prevent showing `admin.ridibooks.com` to search engines.
=> Added a robots.txt

composer.json, composer.lock, src/Service/AdminAuthService.php
- Check host on url auth check: https://rididev.slack.com/archives/CDYB4V69J/p1594108016000500
=> Release 3.0.12
